export const LAST_BIG_UPDATE_TIMESTAMP = new Date(import.meta.env.PUBLIC_LAST_BIG_UPDATE_TIMESTAMP);
export const LAST_OKAY_UPDATE_TIMESTAMP = new Date(import.meta.env.PUBLIC_LAST_OKAY_UPDATE_TIMESTAMP);
