export const LAST_BIG_UPDATE_TIMESTAMP = new Date(import.meta.env.VITE_LAST_BIG_UPDATE_TIMESTAMP);
export const LAST_BIG_UPDATE_PATCH_NOTES_LINK = import.meta.env.VITE_LAST_BIG_UPDATE_PATCH_NOTES_LINK;

export const LAST_OKAY_UPDATE_TIMESTAMP = new Date(import.meta.env.VITE_LAST_OKAY_UPDATE_TIMESTAMP);
export const LAST_OKAY_UPDATE_PATCH_NOTES_LINK = import.meta.env.VITE_LAST_OKAY_UPDATE_PATCH_NOTES_LINK;
